// Deterministic asset resolver generated from the current 81-record Leccy catalogue.
// The catalogue model field is the canonical physical model; variants reuse that asset.

const BRAND_FOLDERS = {
  "Maruti Suzuki": "maruti-suzuki",
  "Rolls-Royce": "rolls-royce"
};

const slugify = (value = "") => {
  const text = String(value).trim();
  if (text === "#1 Pro+" || text.toLowerCase() === "smart #1 pro+") return "1-pro-plus";
  return text.toLowerCase().replace(/#/g, "").replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
};

export const getBrandFolder = (make = "") => BRAND_FOLDERS[make] || slugify(make);

const MODEL_PATHS = {
  "Audi|e-tron": "/vehicles/audi/e-tron.webp",
  "Audi|e-tron GT": "/vehicles/audi/e-tron-gt.webp",
  "Audi|Q8 e-tron": "/vehicles/audi/q8-e-tron.webp",
  "BMW|i4": "/vehicles/bmw/i4.webp",
  "BMW|i5": "/vehicles/bmw/i5.webp",
  "BMW|i7": "/vehicles/bmw/i7.webp",
  "BMW|iX": "/vehicles/bmw/ix.webp",
  "BMW|iX1": "/vehicles/bmw/ix1.webp",
  "BYD|Atto 3": "/vehicles/byd/atto-3.webp",
  "BYD|e6": "/vehicles/byd/e6.webp",
  "BYD|eMAX 7": "/vehicles/byd/emax-7.webp",
  "BYD|Seal": "/vehicles/byd/seal.webp",
  "BYD|Sealion 7": "/vehicles/byd/sealion-7.webp",
  "Citroen|eC3": "/vehicles/citroen/ec3.webp",
  "Hyundai|Creta EV": "/vehicles/hyundai/creta-ev.webp",
  "Hyundai|Ioniq 5": "/vehicles/hyundai/ioniq-5.webp",
  "Jaguar|I-PACE": "/vehicles/jaguar/i-pace.webp",
  "Kia|Carens Clavis EV": "/vehicles/kia/carens-clavis-ev.webp",
  "Kia|EV6": "/vehicles/kia/ev6.webp",
  "Kia|EV9": "/vehicles/kia/ev9.webp",
  "Kia|Syros EV": "/vehicles/kia/syros-ev.webp",
  "Mahindra|BE 6": "/vehicles/mahindra/be-6.webp",
  "Mahindra|XEV 9e": "/vehicles/mahindra/xev-9e.webp",
  "Mahindra|XEV 9S": "/vehicles/mahindra/xev-9s.webp",
  "Mahindra|XUV 3XO EV": "/vehicles/mahindra/xuv-3xo-ev.webp",
  "Mahindra|XUV400": "/vehicles/mahindra/xuv400.webp",
  "Maruti Suzuki|e Vitara": "/vehicles/maruti-suzuki/e-vitara.webp",
  "Mercedes|EQA": "/vehicles/mercedes/eqa.webp",
  "Mercedes|EQB": "/vehicles/mercedes/eqb.webp",
  "Mercedes|EQS": "/vehicles/mercedes/eqs.webp",
  "Mercedes|EQS SUV": "/vehicles/mercedes/eqs-suv.webp",
  "MG|Comet EV": "/vehicles/mg/comet-ev.webp",
  "MG|Cyberster": "/vehicles/mg/cyberster.webp",
  "MG|Hector Tomahawk EV": "/vehicles/mg/hector-tomahawk-ev.webp",
  "MG|M9": "/vehicles/mg/m9.webp",
  "MG|Windsor EV": "/vehicles/mg/windsor-ev.webp",
  "MG|ZS EV": "/vehicles/mg/zs-ev.webp",
  "Mini|Countryman E": "/vehicles/mini/countryman-e.webp",
  "Porsche|Taycan": "/vehicles/porsche/taycan.webp",
  "Rolls-Royce|Spectre": "/vehicles/rolls-royce/spectre.webp",
  "Smart|#1 Pro+": "/vehicles/smart/1-pro-plus.webp",
  "Tata|Curvv EV": "/vehicles/tata/curvv-ev.webp",
  "Tata|Harrier EV": "/vehicles/tata/harrier-ev.webp",
  "Tata|Nexon EV": "/vehicles/tata/nexon-ev.webp",
  "Tata|Punch EV": "/vehicles/tata/punch-ev.webp",
  "Tata|Sierra EV": "/vehicles/tata/sierra-ev.webp",
  "Tata|Tiago EV": "/vehicles/tata/tiago-ev.webp",
  "Tata|Tigor EV": "/vehicles/tata/tigor-ev.webp",
  "Toyota|Urban Cruiser Ebella": "/vehicles/toyota/urban-cruiser-ebella.webp",
  "VinFast|VF 6": "/vehicles/vinfast/vf-6.webp",
  "VinFast|VF 7": "/vehicles/vinfast/vf-7.webp",
  "VinFast|VF MPV 7": "/vehicles/vinfast/vf-mpv-7.webp",
  "Volvo|C40 Recharge": "/vehicles/volvo/c40-recharge.webp",
  "Volvo|XC40 Recharge": "/vehicles/volvo/xc40-recharge.webp",
};

const MODEL_ALIASES = {
  "Audi|e-tron|55 quattro": "e-tron",
  "Audi|e-tron 55 quattro": "e-tron",
  "Audi|e-tron": "e-tron",
  "Audi|e-tron GT|RS": "e-tron GT",
  "Audi|e-tron GT RS": "e-tron GT",
  "Audi|e-tron GT": "e-tron GT",
  "Audi|Q8 e-tron|55 quattro": "Q8 e-tron",
  "Audi|Q8 e-tron 55 quattro": "Q8 e-tron",
  "Audi|Q8 e-tron": "Q8 e-tron",
  "BMW|i4|eDrive40": "i4",
  "BMW|i4 eDrive40": "i4",
  "BMW|i4": "i4",
  "BMW|i5|eDrive40": "i5",
  "BMW|i5 eDrive40": "i5",
  "BMW|i5": "i5",
  "BMW|i7|xDrive60": "i7",
  "BMW|i7 xDrive60": "i7",
  "BMW|i7": "i7",
  "BMW|iX|xDrive50": "iX",
  "BMW|iX xDrive50": "iX",
  "BMW|iX": "iX",
  "BMW|iX1|xDrive30": "iX1",
  "BMW|iX1 xDrive30": "iX1",
  "BMW|iX1": "iX1",
  "BYD|Atto 3|Extended Range": "Atto 3",
  "BYD|Atto 3 Extended Range": "Atto 3",
  "BYD|Atto 3": "Atto 3",
  "BYD|Atto 3|Standard Range": "Atto 3",
  "BYD|Atto 3 Standard Range": "Atto 3",
  "BYD|e6|GL": "e6",
  "BYD|e6 GL": "e6",
  "BYD|e6": "e6",
  "BYD|eMAX 7|Premium": "eMAX 7",
  "BYD|eMAX 7 Premium": "eMAX 7",
  "BYD|eMAX 7": "eMAX 7",
  "BYD|eMAX 7|Superior": "eMAX 7",
  "BYD|eMAX 7 Superior": "eMAX 7",
  "BYD|Seal|Dynamic": "Seal",
  "BYD|Seal Dynamic": "Seal",
  "BYD|Seal": "Seal",
  "BYD|Seal|Performance": "Seal",
  "BYD|Seal Performance": "Seal",
  "BYD|Sealion 7|Premium": "Sealion 7",
  "BYD|Sealion 7 Premium": "Sealion 7",
  "BYD|Sealion 7": "Sealion 7",
  "Citroen|eC3|Feel": "eC3",
  "Citroen|eC3 Feel": "eC3",
  "Citroen|eC3": "eC3",
  "Citroen|eC3|Shine": "eC3",
  "Citroen|eC3 Shine": "eC3",
  "Hyundai|Creta EV|Long Range": "Creta EV",
  "Hyundai|Creta EV Long Range": "Creta EV",
  "Hyundai|Creta EV": "Creta EV",
  "Hyundai|Creta EV|Medium Range": "Creta EV",
  "Hyundai|Creta EV Medium Range": "Creta EV",
  "Hyundai|Ioniq 5|84 kWh AWD": "Ioniq 5",
  "Hyundai|Ioniq 5 84 kWh AWD": "Ioniq 5",
  "Hyundai|Ioniq 5": "Ioniq 5",
  "Hyundai|Ioniq 5|84 kWh RWD": "Ioniq 5",
  "Hyundai|Ioniq 5 84 kWh RWD": "Ioniq 5",
  "Jaguar|I-PACE|EV400": "I-PACE",
  "Jaguar|I-PACE EV400": "I-PACE",
  "Jaguar|I-PACE": "I-PACE",
  "Kia|Carens Clavis EV|42 kWh": "Carens Clavis EV",
  "Kia|Carens Clavis EV 42 kWh": "Carens Clavis EV",
  "Kia|Carens Clavis EV": "Carens Clavis EV",
  "Kia|Carens Clavis EV|51.4 kWh": "Carens Clavis EV",
  "Kia|Carens Clavis EV 51.4 kWh": "Carens Clavis EV",
  "Kia|EV6|84 kWh AWD": "EV6",
  "Kia|EV6 84 kWh AWD": "EV6",
  "Kia|EV6": "EV6",
  "Kia|EV6|84 kWh RWD": "EV6",
  "Kia|EV6 84 kWh RWD": "EV6",
  "Kia|EV9|99.8 kWh": "EV9",
  "Kia|EV9 99.8 kWh": "EV9",
  "Kia|EV9": "EV9",
  "Kia|Syros EV|42 kWh": "Syros EV",
  "Kia|Syros EV 42 kWh": "Syros EV",
  "Kia|Syros EV": "Syros EV",
  "Kia|Syros EV|51.4 kWh": "Syros EV",
  "Kia|Syros EV 51.4 kWh": "Syros EV",
  "Mahindra|BE 6|59 kWh": "BE 6",
  "Mahindra|BE 6 59 kWh": "BE 6",
  "Mahindra|BE 6": "BE 6",
  "Mahindra|BE 6|79 kWh": "BE 6",
  "Mahindra|BE 6 79 kWh": "BE 6",
  "Mahindra|XEV 9e|59 kWh": "XEV 9e",
  "Mahindra|XEV 9e 59 kWh": "XEV 9e",
  "Mahindra|XEV 9e": "XEV 9e",
  "Mahindra|XEV 9e|79 kWh": "XEV 9e",
  "Mahindra|XEV 9e 79 kWh": "XEV 9e",
  "Mahindra|XEV 9S|59 kWh": "XEV 9S",
  "Mahindra|XEV 9S 59 kWh": "XEV 9S",
  "Mahindra|XEV 9S": "XEV 9S",
  "Mahindra|XEV 9S|70 kWh": "XEV 9S",
  "Mahindra|XEV 9S 70 kWh": "XEV 9S",
  "Mahindra|XEV 9S|79 kWh": "XEV 9S",
  "Mahindra|XEV 9S 79 kWh": "XEV 9S",
  "Mahindra|XUV 3XO EV|39.4 kWh": "XUV 3XO EV",
  "Mahindra|XUV 3XO EV 39.4 kWh": "XUV 3XO EV",
  "Mahindra|XUV 3XO EV": "XUV 3XO EV",
  "Mahindra|XUV400|EC Pro": "XUV400",
  "Mahindra|XUV400 EC Pro": "XUV400",
  "Mahindra|XUV400": "XUV400",
  "Mahindra|XUV400|EL Pro": "XUV400",
  "Mahindra|XUV400 EL Pro": "XUV400",
  "Maruti Suzuki|e Vitara|Long Range": "e Vitara",
  "Maruti Suzuki|e Vitara Long Range": "e Vitara",
  "Maruti Suzuki|e Vitara": "e Vitara",
  "Maruti Suzuki|e Vitara|Medium Range": "e Vitara",
  "Maruti Suzuki|e Vitara Medium Range": "e Vitara",
  "Mercedes|EQA|250+": "EQA",
  "Mercedes|EQA 250+": "EQA",
  "Mercedes|EQA": "EQA",
  "Mercedes|EQB|350 4MATIC": "EQB",
  "Mercedes|EQB 350 4MATIC": "EQB",
  "Mercedes|EQB": "EQB",
  "Mercedes|EQS|580 4MATIC": "EQS",
  "Mercedes|EQS 580 4MATIC": "EQS",
  "Mercedes|EQS": "EQS",
  "Mercedes|EQS SUV|580 4MATIC": "EQS SUV",
  "Mercedes|EQS SUV 580 4MATIC": "EQS SUV",
  "Mercedes|EQS SUV": "EQS SUV",
  "MG|Comet EV|Standard": "Comet EV",
  "MG|Comet EV Standard": "Comet EV",
  "MG|Comet EV": "Comet EV",
  "MG|Cyberster|Standard": "Cyberster",
  "MG|Cyberster Standard": "Cyberster",
  "MG|Cyberster": "Cyberster",
  "MG|Hector Tomahawk EV|Standard": "Hector Tomahawk EV",
  "MG|Hector Tomahawk EV Standard": "Hector Tomahawk EV",
  "MG|Hector Tomahawk EV": "Hector Tomahawk EV",
  "MG|M9|Standard": "M9",
  "MG|M9 Standard": "M9",
  "MG|M9": "M9",
  "MG|Windsor EV|38 kWh": "Windsor EV",
  "MG|Windsor EV 38 kWh": "Windsor EV",
  "MG|Windsor EV": "Windsor EV",
  "MG|Windsor EV|52.9 kWh": "Windsor EV",
  "MG|Windsor EV 52.9 kWh": "Windsor EV",
  "MG|ZS EV|Excite": "ZS EV",
  "MG|ZS EV Excite": "ZS EV",
  "MG|ZS EV": "ZS EV",
  "MG|ZS EV|Exclusive": "ZS EV",
  "MG|ZS EV Exclusive": "ZS EV",
  "Mini|Countryman E|ALL4": "Countryman E",
  "Mini|Countryman E ALL4": "Countryman E",
  "Mini|Countryman E": "Countryman E",
  "Porsche|Taycan|4S": "Taycan",
  "Porsche|Taycan 4S": "Taycan",
  "Porsche|Taycan": "Taycan",
  "Porsche|Taycan|Turbo S": "Taycan",
  "Porsche|Taycan Turbo S": "Taycan",
  "Rolls-Royce|Spectre|Standard": "Spectre",
  "Rolls-Royce|Spectre Standard": "Spectre",
  "Rolls-Royce|Spectre": "Spectre",
  "Smart|#1 Pro+|Standard": "#1 Pro+",
  "Smart|#1 Pro+ Standard": "#1 Pro+",
  "Smart|#1 Pro+": "#1 Pro+",
  "Tata|Curvv EV|Long Range": "Curvv EV",
  "Tata|Curvv EV Long Range": "Curvv EV",
  "Tata|Curvv EV": "Curvv EV",
  "Tata|Curvv EV|Medium Range": "Curvv EV",
  "Tata|Curvv EV Medium Range": "Curvv EV",
  "Tata|Harrier EV|65": "Harrier EV",
  "Tata|Harrier EV 65": "Harrier EV",
  "Tata|Harrier EV": "Harrier EV",
  "Tata|Harrier EV|75": "Harrier EV",
  "Tata|Harrier EV 75": "Harrier EV",
  "Tata|Nexon EV|45": "Nexon EV",
  "Tata|Nexon EV 45": "Nexon EV",
  "Tata|Nexon EV": "Nexon EV",
  "Tata|Nexon EV|MR": "Nexon EV",
  "Tata|Nexon EV MR": "Nexon EV",
  "Tata|Nexon EV|Prime": "Nexon EV",
  "Tata|Nexon EV Prime": "Nexon EV",
  "Tata|Punch EV|40": "Punch EV",
  "Tata|Punch EV 40": "Punch EV",
  "Tata|Punch EV": "Punch EV",
  "Tata|Punch EV|Smart": "Punch EV",
  "Tata|Punch EV Smart": "Punch EV",
  "Tata|Sierra EV|63": "Sierra EV",
  "Tata|Sierra EV 63": "Sierra EV",
  "Tata|Sierra EV": "Sierra EV",
  "Tata|Sierra EV|75": "Sierra EV",
  "Tata|Sierra EV 75": "Sierra EV",
  "Tata|Tiago EV|Long Range": "Tiago EV",
  "Tata|Tiago EV Long Range": "Tiago EV",
  "Tata|Tiago EV": "Tiago EV",
  "Tata|Tiago EV|Medium Range": "Tiago EV",
  "Tata|Tiago EV Medium Range": "Tiago EV",
  "Tata|Tigor EV|Ziptron": "Tigor EV",
  "Tata|Tigor EV Ziptron": "Tigor EV",
  "Tata|Tigor EV": "Tigor EV",
  "Toyota|Urban Cruiser Ebella|61 kWh": "Urban Cruiser Ebella",
  "Toyota|Urban Cruiser Ebella 61 kWh": "Urban Cruiser Ebella",
  "Toyota|Urban Cruiser Ebella": "Urban Cruiser Ebella",
  "VinFast|VF 6|59.6 kWh": "VF 6",
  "VinFast|VF 6 59.6 kWh": "VF 6",
  "VinFast|VF 6": "VF 6",
  "VinFast|VF 7|59.6 kWh": "VF 7",
  "VinFast|VF 7 59.6 kWh": "VF 7",
  "VinFast|VF 7": "VF 7",
  "VinFast|VF 7|70.8 kWh": "VF 7",
  "VinFast|VF 7 70.8 kWh": "VF 7",
  "VinFast|VF MPV 7|Standard": "VF MPV 7",
  "VinFast|VF MPV 7 Standard": "VF MPV 7",
  "VinFast|VF MPV 7": "VF MPV 7",
  "Volvo|C40 Recharge|Single Motor": "C40 Recharge",
  "Volvo|C40 Recharge Single Motor": "C40 Recharge",
  "Volvo|C40 Recharge": "C40 Recharge",
  "Volvo|XC40 Recharge|Single Motor": "XC40 Recharge",
  "Volvo|XC40 Recharge Single Motor": "XC40 Recharge",
  "Volvo|XC40 Recharge": "XC40 Recharge",
  "Volvo|XC40 Recharge|Twin Motor": "XC40 Recharge",
  "Volvo|XC40 Recharge Twin Motor": "XC40 Recharge",
  "Mahindra|BE 6 70": "BE 6",
  "Mahindra|BE 6 79": "BE 6",
  "Mahindra|BE 6 59": "BE 6",
  "Mahindra|XEV 9e 59": "XEV 9e",
  "Mahindra|XEV 9e 79": "XEV 9e",
  "Mahindra|XEV 9S 59": "XEV 9S",
  "Mahindra|XEV 9S 70": "XEV 9S",
  "Mahindra|XEV 9S 79": "XEV 9S"
};

const key = (make, model) => `${String(make || "").trim()}|${String(model || "").trim()}`;

export const getPhysicalModel = (make, model) => {
  if (!make || !model) return "";
  return MODEL_ALIASES[key(make, model)] || model;
};

export const getVehicleImage = (make, model) => {
  if (!make || !model) return "/VehicleCard.png";
  const physicalModel = getPhysicalModel(make, model);
  return MODEL_PATHS[key(make, physicalModel)] ||
    `/vehicles/${getBrandFolder(make)}/${slugify(physicalModel)}.webp`;
};

export const getBrandLogo = (make) => {
  if (!make) return null;
  return `/brands/${getBrandFolder(make)}.svg`;
};
